---

- name: 1. disable selinux
  selinux:
    state: disabled

- name: 2. upgrade OS
  yum:
    name: '*'
    state: latest

# vim, nano, mc, firewalld
- name: 3. install default soft
  yum:
    name: "{{item}}"
    state: present
  with_items:
    -  "{{ default_soft_pkg_redhat }}"
  register: install_httpd

- name: 4. Start apache WebServer
  service: 
    name: httpd
    state: started
    enabled: yes

- name: 5. Install config file for example.com and restart httpd
  template:
    src: centos_vhost_conf.j2
    dest: /etc/httpd/conf.d/example.com.conf
    owner: root
    group: root
    mode: 0644
  notify: restart httpd  
#  when: install_httpd.changed
- name: 6. Creating directory for example.com
  file: 
    path: /var/www/html/example.com
    state: directory
    owner: apache
    group: apache
    mode: 0775

- name: 10.Downloading WPress and unachive
  unarchive:
    src: https://wordpress.org/latest.tar.gz 
    dest: /var/www/html/example.com
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: apache
    group: apache
    mode: 0775
  notify: restart httpd

- name: 11.Copy file
  shell: echo "<?php phpinfo (); ?>" > /var/www/html/example.com/info.php
