dependencies: []

galaxy_info:
  author: vostapchuk
  description: Remi's RPM repository for RHEL/CentOS.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - packaging
    - epel
    - repository
    - repo
    - redhat
    - rhel
    - centos