---
- name: 1.Adding epel-release repository to Centos 7
  yum_repository:
    name: epel-release
    state: present

# - name: Add repository
#   yum_repository:
#     name: epel
#     description: EPEL YUM repo
#     baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: 2.Adding mariadb_repo repository
  yum_repository:
    name: mariadb
    file: mariadb
    baseurl: http://yum.mariadb.org/{{mariadb_versions}}/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: 3.Installing MariaDB 
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - "{{ mariadb_redhat }}"

# tasks file for mysql

- name: 4.Creating mysql database
   mysql_db: name={{ mysql_db }} 
   state: present

-  name: 5.Creating mysql user
   mysql_user: 
    name: {{ mysql_user }} 
    password: {{ mysql_password }} 
    priv: *.*:ALL