---
- name: 1.Install requires package for apt module
  become: true
  apt:
    name: python-apt

- name: Add PHP7 ppa repository
  apt_repository: repo='ppa:ondrej/php'

- name: Install php packages
  apt:
    name: php
  notify: apt upgrade

- name: Install php packages
  become: true 
  apt:
    name: "{{ item }}"
  with_items:
    - "{{apt_php_packages}}"
  notify: restart apache2


