---

- name: 1.Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: 2.Install php extensions
  apt: name={{ ['php7.2-gd', 'php7.2-ssh2'] }} state=present
  become: yes


# - name: Add repository for PHP versions (Ubuntu).
#   apt_repository: 
#   repo: 'ppa:ondrej/php'
#   when: ansible_distribution == "Ubuntu"

# - name: Add dependencies for PHP versions (Debian).
#   apt:
#     name:
#       - apt-transport-https
#       - ca-certificates
#     state: present
#   when: ansible_distribution == "Ubuntu"


# - name: Purge PHP version packages.
#   apt:
#     name: "{{ item }}"
#     state: absent
#     purge: true
#     force: true
#   with_items:
#     - php7.2-common


# - name: Check if PHP is installed.
#   command: which php
#   changed_when: false
#   failed_when: false
#   register: php_installed
#   when: ansible_distribution == "Ubuntu"