---
- name: Install remi repo.
  yum:
    name: "{{ remi_repo_url }}"
    # state: present
  notify: yum upgrade

- name: Enable remi repo
  template:
    src: remi-php72.j2
    dest: /etc/yum.repos.d/remi-php72.repo
    mode: 0644
  notify: yum upgrade

- name: Install PHP application
  yum:
    name: php
    state: latest

- name: Install php-modules
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - "{{yum_php_packages}}"
  notify: restart httpd