---
- name: 1.Adding epel-release repository to Centos 7
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      

- name: 2.Installing Remi repository for PHP 7.2
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: 3.Upgrade all packages
  become: true
  yum:
    name: "*"
    state: latest

- name: 4.Install php
  yum:
    name: php72
    state: latest

    # enablerepo: remi

# - name: 4.Start php7-fpm on centos
#   become: true
#   service:
#     name: php-fpm
#     state: started
#     enabled: yes