---

remi_repo_url: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"

yum_php_packages:
  - php-common
  - php-cli
  - php-curl
  - php-json
  - php-mbstring
  - php-mcrypt
  - php-mysql
  - php-xml

apt_php_packages:
  - php-common
  - php-cli
  - php-curl
  - php-json
  - php-mbstring
  - php-mcrypt
  - php-mysql
  - php-xml


